import * as React from 'react';
import type { Context } from '@deepseek-ai/cordis';
import type {} from '@deepseek-ai/dsh-client-connection/client';
import type {} from '@deepseek-ai/dsh-client-ui-slots';
import type {} from '@deepseek-ai/dsh-client-ui-renderer/client';
import type {} from '@deepseek-ai/dsh-client-ui-conversation/client';
import type {} from '@deepseek-ai/dsh-client-ui-layout/client';
import type {} from '@deepseek-ai/dsh-api-session-controller/client';
import type {} from '@deepseek-ai/dsh-api-workspace-controller/client';
import type { ISessions } from '@deepseek-ai/dsh-api-session-controller/client';
import type { ProjectInputRef, ProjectSnapshot } from 'workdsh-contracts/projects';
import { createProjectClient } from './client/management.js'; import { ProjectsPanel } from './client/ProjectsPanel.js';
export const name='workdsh-projects-client'; export const inject=['slots','layout','connection','sessions','workspaces','conversation'];
export function apply(ctx:Context){const lifetime=new AbortController();ctx.effect(()=>()=>lifetime.abort(),'workdsh.projects.client');const management=createProjectClient(lifetime.signal),sessions=ctx.sessions as unknown as ISessions;
const startTask=async(snapshot:ProjectSnapshot,prompt:string,references:readonly ProjectInputRef[])=>{const validated=await management.validateInputRefs(snapshot.project.id,references);const state=sessions.list.getSnapshot(),current=state.current?state.byId[state.current]:undefined,workspaces=ctx.workspaces.list.getSnapshot().items,workspace=workspaces.find(x=>x.sessionIds.includes(state.current!))??workspaces.find(x=>x.path===current?.cwd)??workspaces[0];if(!workspace)throw new Error('请先选择工作空间。');const sessionId=await sessions.create({workspaceId:workspace.workspaceId,cwd:workspace.path});
const invoke=async(path:string,endpoint:string,payload:unknown)=>fetch(path,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({endpoint,payload})});
const selectedAssetIds=new Set(validated.filter(x=>x.kind==='asset').map(x=>x.id)),assets=selectedAssetIds.size?snapshot.assets.filter(x=>selectedAssetIds.has(x.id)):snapshot.assets;if(assets.length)await invoke('/api/workdsh-library','set-task-selection',{sessionId:String(sessionId),nodeIds:assets.map(x=>x.nodeId)}).catch(()=>undefined);
const connectors=snapshot.config.capabilities.filter(x=>x.kind==='connector').map(x=>x.id);if(connectors.length)await invoke('/api/workdsh-connectors','set-selection',{sessionId:String(sessionId),connectorIds:connectors}).catch(()=>undefined);
const selectedSkill=validated.find(x=>x.kind==='skill'),skill=selectedSkill?snapshot.config.capabilities.find(x=>x.kind==='skill'&&x.id===selectedSkill.id):snapshot.config.capabilities.find(x=>x.kind==='skill');const referenceContext=validated.filter(x=>x.kind==='work-item').map(x=>`- 待办：${x.label}（${x.id}，修订 ${x.revision}）`).join('\n');const context=`${snapshot.config.instruction.trim()?`\n\n项目指令（修订 ${snapshot.config.number}）：\n${snapshot.config.instruction.trim()}`:''}${referenceContext?`\n\n本次引用：\n${referenceContext}`:''}`;const draft=`${skill?`/${skill.id} `:''}${prompt}${context}`;const scope=sessions.scope(sessionId),session=scope?sessions.sessionOf(scope):undefined;if(!session)throw new Error('原生会话尚未就绪，请重试。');const result=await session.prompt([{type:'text',text:draft}],'queue',lifetime.signal);if(!result.ok)throw new Error(`提交项目任务失败：${result.error.message}`);await management.linkTask(snapshot.project.id,String(sessionId),prompt.slice(0,80)||snapshot.project.name,undefined,validated);ctx.layout.selectPanel(null);sessions.open(sessionId)};
const openTask=(sessionId:string)=>{ctx.layout.selectPanel(null);sessions.open(sessionId as Parameters<typeof sessions.open>[0])};
ctx.slots.inject('main',()=>ctx.slots.register({name:'main',key:'workdsh-projects',inject:()=>({management,startTask,openTask})},ProjectsPanel));}
