import { modalCss } from 'workdsh-ui';

/** 助理页沿用能力中心的视觉基线（见 docs/UI-DESIGN.md），不另起一套风格。 */
export const assistantCss = `${modalCss}
.wd-assistant{height:100%;overflow:auto;background:var(--dsw-alias-bg-base,#121212);color:var(--dsw-alias-label-primary,#e7e7e7);font:14px/22px "PingFang SC","Microsoft YaHei",sans-serif;padding:24px;box-sizing:border-box}.wd-assistant *{box-sizing:border-box}.wd-assistant button,.wd-assistant input,.wd-assistant textarea{font:inherit;color:inherit}.wd-assistant button{cursor:pointer}.wd-assistant button:disabled{cursor:not-allowed;opacity:.55}.wd-assistant :focus-visible,.assistant-dialog :focus-visible{outline:2px solid var(--dsw-alias-label-primary,#ddd);outline-offset:3px}
.wd-assistant .cap-header{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:28px}.wd-assistant .search{margin-left:auto;width:250px;min-width:150px;min-height:36px;padding:6px 12px;border:.5px solid var(--dsw-alias-border-l1,#343434);border-radius:8px;background:var(--dsw-alias-bg-layer-2,#242424);color:var(--dsw-alias-label-primary,#eee)}
.wd-assistant .assistant-head{display:flex;align-items:center;gap:14px;margin-bottom:20px;padding-bottom:18px;border-bottom:.5px solid var(--dsw-alias-border-l1,#303030)}.wd-assistant .title-icon{display:grid;place-items:center;width:44px;height:44px;border:1px solid #3a4656;border-radius:12px;background:#1f2935;color:#9bc4ff}.wd-assistant .title-icon svg{width:20px;height:20px}.wd-assistant .assistant-head h1{margin:0;font-size:25px;line-height:34px;font-weight:600}.wd-assistant .assistant-head p{margin:2px 0 0;color:var(--dsw-alias-label-secondary,#a5a5a5)}.wd-assistant .head-actions{display:flex;gap:8px;margin-left:auto}.wd-assistant .secondary,.wd-assistant .primary{min-height:36px;padding:6px 12px;border:.5px solid var(--dsw-alias-border-l2,#343434);border-radius:8px;background:var(--dsw-alias-bg-layer-2,#242424)}.wd-assistant .primary{background:var(--dsw-alias-button-primary-fill,#eee);border-color:var(--dsw-alias-button-primary-fill,#eee);color:var(--dsw-alias-label-primary-inverted,#171717);font-weight:600}
.wd-assistant .tabs{display:flex;gap:8px;margin-bottom:16px}.wd-assistant .tabs button{min-height:32px;padding:4px 12px;border:.5px solid transparent;border-radius:999px;corner-shape:round;background:transparent;color:var(--dsw-alias-label-secondary,#a5a5a5)}.wd-assistant .tabs button.active{border-color:var(--dsw-alias-border-l2,#343434);background:var(--dsw-alias-bg-layer-3,#303030);color:var(--dsw-alias-label-primary,#eee)}
.wd-assistant .list-meta{display:flex;align-items:center;justify-content:space-between;margin:0 0 16px}.wd-assistant .list-meta strong{font-size:15px}.wd-assistant .count{display:inline-grid;place-items:center;min-width:24px;height:24px;margin-left:7px;border-radius:999px;corner-shape:round;background:var(--dsw-alias-bg-layer-3,#303030);color:var(--dsw-alias-label-secondary,#cfcfcf)}.wd-assistant .muted{color:var(--dsw-alias-label-secondary,#a5a5a5)}
.wd-assistant .assistant-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:22px}.wd-assistant .assistant-card{position:relative;min-width:0;min-height:150px;padding:16px;display:flex;flex-direction:column;gap:8px;border:.5px solid var(--dsw-alias-border-l1,#292929);border-radius:18px;background:var(--dsw-alias-bg-layer-2,#242424);text-align:left}.wd-assistant .assistant-card:hover{border-color:var(--dsw-alias-border-l2,#3b3b3b);background:var(--dsw-alias-interactive-bg-hover-solid,#282828)}.wd-assistant .assistant-card.archived{opacity:.6}.wd-assistant .card-title{display:flex;align-items:center;gap:10px;min-width:0}.wd-assistant .card-title strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:600;font-size:17px}.wd-assistant .card-body{margin:0;color:var(--dsw-alias-label-primary,#d5d5d5);font-size:14px;line-height:22px;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.wd-assistant .card-foot{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:auto;padding-top:10px;color:var(--dsw-alias-label-caption,#8f8f8f);font-size:12px}.wd-assistant .badge{display:inline-flex;align-items:center;gap:5px;padding:2px 8px;border-radius:999px;corner-shape:round;background:var(--dsw-alias-bg-layer-3,#303030);font-size:11px}.wd-assistant .badge.warn{background:color-mix(in srgb,var(--dsw-alias-state-warn-primary,#efb44f) 18%,transparent);color:var(--dsw-alias-state-warn-primary,#efb44f)}
.wd-assistant .empty{padding:64px 20px;text-align:center;color:var(--dsw-alias-label-secondary,#aaa)}.wd-assistant .error,.assistant-dialog .error{color:var(--dsw-alias-state-error-primary,#ffb4ab)}.wd-assistant code,.assistant-dialog code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--dsw-alias-label-primary-bluish,#a8c9ff)}
.assistant-dialog{width:min(760px,calc(100vw - 32px));padding:24px}.assistant-dialog.wide{width:min(920px,calc(100vw - 32px))}.assistant-dialog h1{margin:0;padding-right:44px;font-size:20px}.assistant-dialog p{color:var(--dsw-alias-label-secondary,#aaa)}.assistant-dialog .hero{display:flex;align-items:center;gap:14px;margin-bottom:8px}.assistant-dialog .hero .mark{display:grid;place-items:center;width:46px;height:46px;flex:none;border-radius:12px;background:linear-gradient(145deg,#2b4a7c,#4f8ce0);font-size:19px;font-weight:700;text-transform:uppercase}
.assistant-dialog .section{margin-top:16px;padding:14px;border:.5px solid var(--dsw-alias-border-l2,#343434);border-radius:12px;background:var(--dsw-alias-bg-layer-2,#242424)}.assistant-dialog .section h2{margin:0 0 10px;font-size:13px;font-weight:600;color:var(--dsw-alias-label-secondary,#a5a5a5);letter-spacing:.04em}.assistant-dialog .field{margin:0 0 8px;color:var(--dsw-alias-label-primary,#dcdcdc);white-space:pre-wrap}.assistant-dialog .field:last-child{margin-bottom:0}.assistant-dialog .field small{display:block;color:var(--dsw-alias-label-caption,#888)}
.assistant-dialog .ref-list{display:flex;flex-direction:column;gap:8px;margin:0;padding:0;list-style:none}.assistant-dialog .ref-list li{display:flex;align-items:center;gap:10px;padding:9px 11px;border-radius:9px;background:var(--dsw-alias-bg-layer-1,#181818)}.assistant-dialog .ref-kind{flex:none;padding:1px 7px;border-radius:999px;corner-shape:round;background:var(--dsw-alias-bg-layer-3,#303030);color:var(--dsw-alias-label-secondary,#bdbdbd);font-size:11px}.assistant-dialog .ref-name{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.assistant-dialog .ref-note{margin-left:auto;flex:none;font-size:12px;color:var(--dsw-alias-label-caption,#8f8f8f)}.assistant-dialog .ref-note.bad{color:var(--dsw-alias-state-warn-primary,#efb44f)}.assistant-dialog .ref-remove{flex:none;border:0;background:transparent;color:var(--dsw-alias-label-caption,#999)}
.assistant-dialog .form{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:18px}.assistant-dialog .form label{display:grid;gap:6px;color:var(--dsw-alias-label-secondary,#aaa);font-size:12px}.assistant-dialog .form label.wide,.assistant-dialog .form .wide{grid-column:1/-1}.assistant-dialog input,.assistant-dialog select,.assistant-dialog textarea{width:100%;padding:10px 12px;border:.5px solid var(--dsw-alias-border-l2,#404040);border-radius:9px;background:var(--dsw-specific-input-major,#171717);color:var(--dsw-alias-label-primary,#eee);font:14px/20px inherit}.assistant-dialog textarea{min-height:76px;resize:vertical}.assistant-dialog .picker{display:flex;gap:8px;align-items:center}.assistant-dialog .picker select{flex:1}.assistant-dialog .form-note{grid-column:1/-1;padding:11px 13px;border-radius:9px;background:var(--dsw-alias-bg-base,#181818);color:var(--dsw-alias-label-caption,#888);font-size:12px}.assistant-dialog .checks{display:flex;gap:18px;align-items:center;flex-wrap:wrap;color:var(--dsw-alias-label-secondary,#c5c5c5)}.assistant-dialog .checks label{display:flex;gap:7px;align-items:center}.assistant-dialog .checks input{width:auto}.assistant-dialog .form-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:18px}.assistant-dialog button{min-height:38px;padding:7px 14px;border:.5px solid var(--dsw-alias-border-l3,#414141);border-radius:9px;background:var(--dsw-alias-bg-layer-2,#242424);color:var(--dsw-alias-label-primary,#eee)}.assistant-dialog button.primary{background:var(--dsw-alias-button-primary-fill,#eee);border-color:var(--dsw-alias-button-primary-fill,#eee);color:var(--dsw-alias-label-primary-inverted,#171717);font-weight:600}
.wd-assistant .nav-toggle{display:none}
@media(max-width:1400px){.wd-assistant .assistant-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:900px){.wd-assistant .assistant-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.wd-assistant .search{order:2;margin-left:0;flex:1}.wd-assistant .head-actions{width:100%;margin-left:58px}}@media(max-width:560px){.wd-assistant{padding:16px}.wd-assistant .nav-toggle{display:block}.wd-assistant .assistant-grid{grid-template-columns:1fr}.wd-assistant .assistant-head{align-items:flex-start;flex-wrap:wrap}.wd-assistant .head-actions{margin-left:0}.assistant-dialog .form{grid-template-columns:1fr}}
`;
